server:
  port: 8087
spring:
  application:
    name: Product Service
  datasource:
    url: jdbc:h2:mem:testdb;
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          max-attempts: 3
          enabled: true
    virtual-host: /
